version: "3.9"

services:
  odoo1:
    # image: novobidevops/odoo:16
    build: ./box
    ports:
      - "8068:8069"
    volumes:
      - ./:/opt/odoo
      - odoo1_data:/home/odoo/.local/share/Odoo
    command: bash -c "$${PYTHON_PATH} $${START_ODOO} $${ODOO_PARAM} && tail -f /dev/null"
    environment:
      PYTHON_PATH: "/usr/bin/python3"
      START_ODOO: "/opt/odoo/odoo/odoo-bin -c /opt/odoo/odoo1.conf"
      ODOO_PARAM: ""
    depends_on:
      - odoo1-postgres
    tty: true
  odoo1-postgres:
    image: postgres:13
    ports:
      - "5431:5432"
    volumes:
      - odoo1_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    tty: true
  odoo2:
    # image: novobidevops/odoo:16
    build: ./box
    ports:
      - "8069:8069"
    volumes:
      - ./:/opt/odoo
      - odoo2_data:/home/odoo/.local/share/Odoo
    command: bash -c "$${PYTHON_PATH} $${START_ODOO} $${ODOO_PARAM} && tail -f /dev/null"
    environment:
      PYTHON_PATH: "/usr/bin/python3"
      START_ODOO: "/opt/odoo/odoo/odoo-bin -c /opt/odoo/odoo2.conf"
      ODOO_PARAM: ""
    depends_on:
      - odoo2-postgres
    tty: true
  odoo2-postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - odoo2_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    tty: true
  oms:
    build: ./box
    ports:
      - "8070:8069"
    volumes:
      - ./:/opt/odoo
      - oms_data:/home/odoo/.local/share/Odoo
    command: bash -c "$${PYTHON_PATH} $${START_ODOO} $${ODOO_PARAM} && tail -f /dev/null"
    environment:
      PYTHON_PATH: "/usr/bin/python3"
      START_ODOO: "/opt/odoo/odoo/odoo-bin -c /opt/odoo/oms.conf"
      ODOO_PARAM: ""
    depends_on:
      - oms-postgres
    tty: true
  oms-postgres:
    image: postgres:13
    ports:
      - "5433:5432"
    volumes:
      - oms_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    tty: true
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  odoo1_data:
  odoo1_postgres_data:
  odoo2_data:
  odoo2_postgres_data:
  oms_data:
  oms_postgres_data:
